language: r
r:
  - bioc-release
sudo: true
cache: packages
bioc_required: true
bioc_use_devel: true
warnings_are_errors: false

os:
  - linux
  - osx
osx_image: xcode9

os:
  - linux
  - osx
osx_image: xcode9

r_binary_packages:
  - withr
  - knitr
  - crayon
  - roxygen2
  - testthat
  - rex
  - survminer
  - R6
  - whisker
  - jsonlite
  - httr
  - RCurl
  - bitops
  - DBI
  - getopt
  - rjson
  - snow
  - RSQLite
  - base64enc
  - fastmatch
  - XML
  - igraph

bioc_packages:
  - BiocStyle
  - EDASeq
  - edgeR
  - biomaRt
  - supraHex
  - ComplexHeatmap
  - SummarizedExperiment
  - TxDb.Hsapiens.UCSC.hg19.knownGene
  - limma
  - genefilter
  - ConsensusClusterPlus
  - pathview
  - clusterProfiler
  - BiocCheck
  - fgsea
  - GO.db
  - DO.db
  - org.Hs.eg.db
  - GenomicRanges
  - Biobase
  - S4Vectors
  - IRanges
  - BiocGenerics
  - GenomicFeatures
  - affy

r_github_packages:
  - kevinushey/later
  - hfang-bristol/dnet
  - PoisonAlien/maftools
  - r-lib/later

after_script:
  - ls -lah
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")


after_failure:
  - ./travis-tool.sh dump_logs


notifications:
  slack: omics-team:mp8k727GslFLZPQrmuvOkCcc
  email: false
